### ISSUE TITLE
Question regarding the rule engine

### ISSUE THREAD

**Issue by richiesgr** [maxant/rules#1]
Hi

The project seems very interesting and I try to use it for my use case but I don't know if it's maching.
My use case is to receive a list of input and choose between **_all these inputs**_ the best matching to the rules.

So the outcome mechanism doesn't work for me. The action mechanism neither because all is related to find the rules matching the input.

My be I don't understand this enough could you help ?
Thanks

**Comment by mallond** [comment]
Hi Rich,

Wow - someone pinged me with this, I am little surprised. Your feedback is
welcomed.

I have a vision of creating a 'Real Rules Engine', however; this example is
but a toy and a concept that I wanted to play with. The vision is that
rules engines should not be so scientific (the graph theory folk over think
this stuff).

One of these days I will post a hardened and 'Real World' functioning
version.

Cheers,


Kind regards,

David Mallon
702-335-3621

[image: --]
david mallon
[image: http://]about.me/davidmallon
<http://about.me/davidmallon>

**Comment by richiesgr** [comment]
Hi David

Happy to know this. Do you think that you'll address my issue ?
I would like to match the input with the rules not with outcome or action related to rules.
I think it's requires new API to the engine

**Comment by maxant** [comment]
Hi @richiesgr ,

For your problem, I would do something like this:

1) add rules to engine
2) for each input, run it against the engine to retrieve the matching rules.
3) map each matching rule to a score
4) sum the scores - that is the result for a single input
5) repeat 2-4 for each input
6) take the input which had the best result.

Code might look something like this:

```
static final Map<Rule, Integer> SCORES = new HashMap<>();
SCORES.put(rule1, 30);
SCORES.put(rule2, 50);
//etc...

int bestScore = Integer.MINIMUM;
Input bestInput = null;
for(Input i : inputs){
    List<Rule> matchingRules = engine.getMatchingRules(i);
    int score = matchingRules.toStream().map(r -> SCORES.get(r).sum();
    if(score > bestScore){
        bestScore = score;
        bestInput = i;
    }
}

//now use bestInput...
```

Would that satisfy your requirements?

**Comment by richiesgr** [comment]
Of course it seems to be ok 

my first question : it is not heavy to process like this ? I want to use it in low latency application based on Akka
Second question: is it thread safe at the engine level and MEVL itself? ( do I need to instanciate each time a new engine ?)

Thanks

**Comment by mallond** [comment]
Me too. Don't know how I got on this thread. Disregard please.

**Comment by maxant** [comment]
See `DefaultEngineTest.testMultithreadingAndPerformance()` (https://github.com/maxant/rules/blob/master/rules/src/test/java/ch/maxant/rules/blackbox/DefaultEngineTest.java) => yes it is threadsafe and fast using MVEL. You do NOT need to instantiate several engines - just create one, as in the test.
